{
 "title": "DCX Avionics Overview",
 "tags": [
  "Overview",
  "DCX",
  "Sub-Orbital"
 ],
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Altitude",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "surface_altitude", "legendFormat": "surface_altitude" },
    { "expr": "altitude", "legendFormat": "altitude" }
   ]
  },
  {
   "title": "Velocity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "velocity", "legendFormat": "velocity" },
    { "expr": "vertical_vel", "legendFormat": "vertical_vel" },
    { "expr": "horizontal_vel", "legendFormat": "horizontal_vel" }
   ]
  },
  {
   "title": "Landing Params",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "distance_to_pad", "legendFormat": "distance_to_pad" },
    { "expr": "current_horizontal_velocity", "legendFormat": "current_horizontal_velocity" }
   ]
  },
  {
   "title": "Throttle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "throttle", "legendFormat": "throttle" }
   ]
  },
  {
   "title": "GNC mode 2a - Target Tracking Close",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "distance_pitch", "legendFormat": "distance_pitch" },
    { "expr": "velocity_pitch", "legendFormat": "velocity_pitch" },
    { "expr": "pitch_input", "legendFormat": "pitch_input" }
   ]
  },
  {
   "title": "GNC mode 2b -Target Tracking Far",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pitch_input", "legendFormat": "pitch_input" },
    { "expr": "heading_error", "legendFormat": "heading_error" },
    { "expr": "roll", "legendFormat": "roll" },
    { "expr": "roll_input", "legendFormat": "roll_input" }
   ]
  },
  {
   "title": "GNC mode 3 - Final Landing Approach",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pitch", "legendFormat": "pitch" },
    { "expr": "alt_controller_setpoint", "legendFormat": "alt_controller_setpoint" },
    { "expr": "vert_vel_setpoint", "legendFormat": "vert_vel_setpoint" },
    { "expr": "time_to_burn", "legendFormat": "time_to_burn" }
   ]
  },
  {
   "title": "GNC Framerate (FPS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gnc_frame_count_total[1s])",
     "legendFormat": "frames per second"
    },
    {
     "expr": "rate(gnc_overrun_count_total[1s])",
     "legendFormat": "overruns per second"
    }
   ]
  },
  {
   "title": "Control Mode",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "control_mode{} > 0", "legendFormat": "control_mode" }
   ]
  },
  {
   "title": "GNC Function time (p95)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(calculate_landing_burn_time_bucket[1s]))",
     "legendFormat": "calculate_landing_burn_time"
    },
    {
     "expr": "histogram_quantile(0.95, rate(calculate_heading_bucket[1s]))",
     "legendFormat": "calculate_heading"
    },
    {
     "expr": "histogram_quantile(0.95, rate(haversine_distance_bucket[1s]))",
     "legendFormat": "haversine_distance"
    },
    {
     "expr": "histogram_quantile(0.95, rate(publish_gnc_metrics_b_bucket[1s]))",
     "legendFormat": "publish_gnc_metrics_b"
    },
    {
     "expr": "histogram_quantile(0.95, rate(get_flight_path_angle_bucket[1s]))",
     "legendFormat": "get_flight_path_angle"
    },
    {
     "expr": "histogram_quantile(0.95, rate(calc_lb_final_math_bucket[1s]))",
     "legendFormat": "calc_lb_final_math"
    },
    { "expr": "1 / 50", "legendFormat": "50 hz frametime" },
    { "expr": "1 / 30", "legendFormat": "30 hz frametime" }
   ]
  }
 ]
}