{
 "title": "Orbital Launch Overview",
 "tags": [
  "Overview",
  "Orbital",
  "Minerva",
  "Maxerva",
  "Hurley",
  "F9"
 ],
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Altitude",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "surface_altitude", "legendFormat": "surface_altitude" },
    { "expr": "altitude", "legendFormat": "altitude" }
   ]
  },
  {
   "title": "Velocity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "velocity", "legendFormat": "velocity" },
    { "expr": "vertical_vel", "legendFormat": "vertical_vel" },
    { "expr": "horizontal_vel", "legendFormat": "horizontal_vel" }
   ]
  },
  {
   "title": "Orbital Parameters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "apoapsis", "legendFormat": "apoapsis" },
    { "expr": "periapsis", "legendFormat": "periapsis" }
   ]
  },
  {
   "title": "Control Mode",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 30, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "control_mode{} > 0", "legendFormat": "control_mode" }
   ]
  }
 ]
}