apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    isDefault: true
    jsonData:
      version: "Flux"
      organization: "example_org"
      defaultBucket: "telem_bucket"
    secureJsonData:
      token: "admintoken"